### ISSUE TITLE
join rbind

### ISSUE THREAD

**Issue by michielvandijk** [rbind/support#77]
Hi,
A few days ago I became aware of blogdown through rbloggers. Today I read the blog by Alison on how to build an academic website and started to build my own website, trying to learn the package. 

As a researcher working at IIASA (http://www.iiasa.ac.at/) and Wageningen University I am using R on a daily basis. Hence, having my own website on rbind that I can easily manage with R would be great - great initiative by the way. In other words, I hope I can join (academic theme please).
Best,
Michiel

**Comment by yihui** [comment]
@thercast Could you take care of this? Thanks!

**Comment by thercast** [comment]
@michielvandijk I've set up a `blogdown` site repository for you at [github.com/rbind/michielvandijk](https://github.com/rbind/michielvandijk) and you should receive an invitation by email to join the `rbind` org.  I gave you the academic theme, but you'll need to make tweaks to personalize the site to your desired content.  Did you want us to secure a domain on `rbind` for you as well?  If so what would be your desired domain name for the site?

**Comment by michielvandijk** [comment]
Hi Eric,
Thanks! Yes! Please reserve a "michielvandijk" domain for me. I would like to use this for my academic website.

Cheers,
Michiel

Sent from my iPhone

On 16 Sep 2017, at 04:41, Eric Nantz <notifications@github.com<mailto:notifications@github.com>> wrote:


@michielvandijk<https://github.com/michielvandijk> I've set up a blogdown site repository for you at github.com/rbind/michielvandijk<https://github.com/rbind/michielvandijk> and you should receive an invitation by email to join the rbind org. I gave you the academic theme, but you'll need to make tweaks to personalize the site to your desired content. Did you want us to secure a domain on rbind for you as well? If so what would be your desired domain name for the site?

-

**Comment by thercast** [comment]
Sounds good, we'll be glad to give you the domain of `michielvandijk.rbind.io`.  @yihui  Could you secure a DNS record for this?

**Comment by yihui** [comment]
@michielvandijk I can give you the rbind subdomain, but you need to tell me your Netlify subdomain first.

**Comment by michielvandijk** [comment]
I have not worked with Netlify yet so I need to get into it first. I also read you might be able to set it up for me (quicker :-). If you can, please do. If not I will try to find out how it works tomorrow. Thanks!

**Comment by thercast** [comment]
@michielvandijk I forgot to mention that I set you up with netlify already.  The temporary URL is <https://governor-governors-35321.netlify.com/> .  @yihui the strange part is when I browse the netlify URL I get an error about page not found, even though locally the site looked to be built just fine.  I did change the `baseURL` to the desired rbind address so perhaps once we get the DNS resolved it will _just work_ ™️

**Comment by yihui** [comment]
@thercast Could you check the deploy log and verify if it actually succeeded? I have configured the rbind subdomain, but you are likely to have to contact Netlify support to make it work (#42).

**Comment by michielvandijk** [comment]
Deployment works fine but when I want to set up my personal domain and fill out the rbind one, I got the message that it is already in use. Not sure if you still need to link my netlify domain to rbind or if it is simular to #42. In any case I have sent them a message. This is my netlify domain name in case you still need to link it to the rbind one: https://michielvandijk.netlify.com

**Comment by yihui** [comment]
@michielvandijk Same issue as #42.

**Comment by thercast** [comment]
@michielvandijk I tried re-doing the deployment and ran in to the same issue as you when assigning the custom domain.  I have contacted Netlify support and I will update you when I get a response back.

**Comment by yihui** [comment]
Since you both created a site from the same repo but used different Netlify subdomains, I don't know which subdomain I should use. Currently I'm pointing `michielvandijk.rbind.io` to `michielvandijk.netlify.com`, so @thercast's site may not work. You can let @michielvandijk contact Netlify support.

**Comment by michielvandijk** [comment]
Indeed, there seems to be a mixup up between the two versions when I try to deploy – still getting a warning about a duplicate. I contacted Netlify again and asked them to link to my version.

**Comment by thercast** [comment]
Sorry for causing so much trouble in this process :disappointed: I made sure the site I deployed does not request a custom domain (I tried deleting it from the rbind netlify site list but it appears I don't have sufficient permission).  @michielvandijk hopefully you can find a resolution with the netlify support team and they can figure out why `michielvandijk.rbind.io` is not able to be assigned.

**Comment by michielvandijk** [comment]
I think most of the problems are solved now. I fixed some settings on Netlify for continuous deployment and it seems my website is being built straight from my github rbind repo. However, I still face a problem when using blogdown on my laptop. When I run: blogdown:::serve_site() on my laptop I get the error below. Also when I run the add on I get an error : the system cannot find the file specified. Any ideas?


blogdown:::serve_site()

Error: unknown command "#" for "hugo"

Run 'hugo --help' for usage.

Error: unknown command "#" for "hugo"

Run 'hugo --help' for usage.

The filename, directory name, or volume label syntax is incorrect.

Error in shell(cmd, mustWork = TRUE, intern = intern) :

  '"C:\Users\dijk158\AppData\Roaming\Hugo\hugo.exe" -b /"https://michielvandijk.rbind.io/"  # End your URL with a `/` trailing slash. -D -F -d "public" -t hugo-academic' execution failed with error code 1



[cid:image001.png@01D33338.2D8BFB10]

**Comment by yihui** [comment]
@michielvandijk As I mentioned in the blogdown announcement (https://blog.rstudio.com/2017/09/11/announcing-blogdown/):

> [...] Since blogdown is a new package, you may install and test the development version using `devtools::install_github("rstudio/blogdown")` if you run into problems with the CRAN version.

**Comment by michielvandijk** [comment]
Good advice. That solved one issue! The serve_site() works fine now. The other issue still remains but I have a feeling that this is perhaps more general. When I run another addin: update_metadata. I get: Error in `Encoding<-`(`*tmp*`, value = "UTF-8") :
  a character vector argument expected
Same issue with the bookdown addin and some others. Any suggestions?

**Comment by yihui** [comment]
Could you provide a minimal and reproducible example? I only need the YAML metadata of the post.

**Comment by michielvandijk** [comment]
Is this what you need? Not much info I guess:
---
title: Test to reproduce error
author: test
date: '2017-09-22'
slug: test-to-reproduce-error
categories: []
tags: []
header:
  caption: ''
  image: ''

**Comment by yihui** [comment]
And your session info?

```r
devtools::session_info('blogdown')
```

Does the problem occur as soon as you click the addin?

**Comment by michielvandijk** [comment]
Some additional things I found out by coincidence. When I have the markdown file open (e.g the .md file I just sent), the addins work (e.g. update metadata, preview book)! Adding a new post does work, like before but still gives the same error as shown by the screenshot shared before.

**Comment by michielvandijk** [comment]
See session info below. To be clear, I encounter two (possibly related) errors.
The first is that the addin do not work when I do not have a file open but as soon as I open an .rmd file it works. Example (simply opening an rmd file between the two update statements):
blogdown:::update_meta_addin()
Error in `Encoding<-`(`*tmp*`, value = "UTF-8") : 
  a character vector argument expected
> blogdown:::update_meta_addin()

Listening on http://127.0.0.1:3604

The second is that running the addin new post works but also gives the little screen with the error.



> devtools::session_info('blogdown')
Session info --------------------------------------------------------------------------------
setting  value                       
 version  R version 3.4.1 (2017-06-30)
system   x86_64, mingw32             
 ui       RStudio (1.0.153)           
 language (EN)                        
 collate  English_United Kingdom.1252 
 tz       Europe/Berlin               
 date     2017-09-22                  

Packages ------------------------------------------------------------------------------------
package   * version date       source                           
 backports   1.1.0   2017-05-22 CRAN (R 3.4.1)                   
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.1)                   
 bitops      1.0-6   2013-08-17 CRAN (R 3.4.1)                   
 blogdown    0.1.4   2017-09-21 Github (rstudio/blogdown@8c9c480)
bookdown    0.5     2017-08-20 CRAN (R 3.4.1)                   
 caTools     1.17.1  2014-09-10 CRAN (R 3.4.1)                   
 digest      0.6.12  2017-01-27 CRAN (R 3.4.1)                   
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.1)                   
 graphics  * 3.4.1   2017-06-30 local                            
 grDevices * 3.4.1   2017-06-30 local                            
 highr       0.6     2016-05-09 CRAN (R 3.4.1)                   
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.1)                   
 httpuv      1.3.5   2017-07-04 CRAN (R 3.4.1)                   
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.1)                   
 knitr       1.17    2017-08-10 CRAN (R 3.4.1)                   
 magrittr    1.5     2014-11-22 CRAN (R 3.4.1)                   
 markdown    0.8     2017-04-20 CRAN (R 3.4.1)                   
 methods   * 3.4.1   2017-06-30 local                            
 mime        0.5     2016-07-07 CRAN (R 3.4.1)                   
 Rcpp        0.12.12 2017-07-15 CRAN (R 3.4.1)                   
 rmarkdown   1.6     2017-06-15 CRAN (R 3.4.1)                   
 rprojroot   1.2     2017-01-16 CRAN (R 3.4.1)                   
 servr       0.7     2017-08-17 CRAN (R 3.4.1)                   
 stats     * 3.4.1   2017-06-30 local                            
 stringi     1.1.5   2017-04-07 CRAN (R 3.4.1)                   
 stringr     1.2.0   2017-02-18 CRAN (R 3.4.1)                   
 tools       3.4.1   2017-06-30 local                            
 utils     * 3.4.1   2017-06-30 local                            
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.1) 



________________________________________

**Comment by michielvandijk** [comment]
and some other info, which might be relevant. When I run serve_site, there is a difference in how .Rmd and .md files are treated. .html files of .Rmd files are (wrongly) placed in the post folder while and an additiional message is printed (e.g. Rendering content/post/2017-09-21-test.Rmd) while .html files of .md files are placed in public/post sub folders. 
 ________________________________________

**Comment by yihui** [comment]
@michielvandijk You seem to have reported several issues about blogdown, but I don't completely understand them. Could you file them separately to https://github.com/rstudio/blogdown/issues? Note you have been replying to an issue in the rbind repo, which is not meant to be the help desk of blogdown (https://support.rbind.io/about/). Please also note that since you are replying through emails, none of your attachments or images will come through. When you have anything else other than pure text to show, you have to come back to Github to insert them.
